const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createApp } = require('./server');

test('admin authentication, protected uploads, validation, persistence and logout', async () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ikm-test-'));
  let server; let base;
  const start = async () => { server = await createApp({ dataDir }); await new Promise(resolve => server.listen(0,'127.0.0.1',resolve)); base = `http://127.0.0.1:${server.address().port}`; };
  const stop = async () => { await new Promise(resolve => { server.close(resolve); server.closeAllConnections(); }); };
  const request = (url, method = 'GET', value, cookie, headers = {}) => fetch(base + url, { method, headers: { 'Content-Type':'application/json', 'X-IKM-Request':'1', ...(cookie ? { Cookie:cookie } : {}), ...headers }, ...(value === undefined ? {} : { body:JSON.stringify(value) }) });
  try {
    await start();
    const password = fs.readFileSync(path.join(dataDir,'initial-admin.txt'),'utf8').match(/Password: (.+)/)[1];
    const credentials = { username:'admin', password };
    const album = { title:'Kebersamaan <IKM>', category:'Seminar', date:'2026-09-17', driveUrl:'https://drive.google.com/drive/folders/example_folder', thumbnail:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=' };
    assert.equal((await request('/api/albums','POST',album)).status,401);
    assert.equal((await request('/api/login','POST',{ username:'admin', password:'wrong' })).status,401);
    assert.equal((await request('/api/login','POST',credentials,undefined,{ Origin:'https://foreign.example' })).status,403);
    assert.equal((await fetch(base + '/api/login',{ method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(credentials) })).status,403);
    const login = await request('/api/login','POST',credentials);
    assert.equal(login.status,200);
    const cookieHeader = login.headers.get('set-cookie'); assert.match(cookieHeader,/HttpOnly/); assert.match(cookieHeader,/SameSite=Strict/);
    const cookie = cookieHeader.split(';')[0];
    const information = { title:'Pengumuman <IKM>', content:'Pendaftaran dibuka.\nSilakan baca lampiran.', attachment:{ name:'pengumuman.pdf', data:'data:application/pdf;base64,' + Buffer.from('%PDF-1.4\n%%EOF').toString('base64') } };
    assert.equal((await request('/api/information','POST',information)).status,401);
    assert.equal((await request('/api/information','POST',information,cookie,{ Origin:'https://foreign.example' })).status,403);
    for (const change of [{ title:' ' },{ content:'' },{ content:'x'.repeat(10001) },{ attachment:{ name:'bad.pdf',data:'data:application/pdf;base64,AAAA' } },{ attachment:{ name:'bad.html',data:'data:text/html;base64,PHNjcmlwdD4=' } }]) assert.equal((await request('/api/information','POST',{ ...information,...change },cookie)).status,400);
    assert.equal((await request('/api/information','POST',{ ...information,attachment:{ name:'large.pdf',data:'data:application/pdf;base64,' + Buffer.alloc(5 * 1024 * 1024 + 1).toString('base64') } },cookie)).status,413);
    const published = await request('/api/information','POST',information,cookie); assert.equal(published.status,201);
    const announcement = (await published.json()).information;
    assert.equal(announcement.attachment.data,undefined);
    const download = await request(announcement.attachment.url);
    assert.equal(download.status,200); assert.equal(download.headers.get('content-type'),'application/pdf'); assert.match(download.headers.get('content-disposition'),/^attachment;/);
    assert.equal(await download.text(),'%PDF-1.4\n%%EOF');
    const textOnly = await request('/api/information','POST',{ title:'Tanpa lampiran',content:'Informasi teks.' },cookie);
    assert.equal(textOnly.status,201); const textId = (await textOnly.json()).information.id;
    const imageInfo = await request('/api/information','POST',{ ...information,attachment:{ name:'poster.png',data:album.thumbnail } },cookie);
    assert.equal(imageInfo.status,201); const imageItem = (await imageInfo.json()).information;
    assert.equal((await request(imageItem.attachment.url)).headers.get('content-type'),'image/png');
    assert.equal((await request('/api/information/' + announcement.id,'DELETE')).status,401);
    assert.equal((await (await request('/api/session','GET',undefined,cookie)).json()).authenticated,true);
    for (const url of ['/data/admin.json','/data/initial-admin.txt','/data/albums.json','/server.js','/README.md','/.env','/assets/../data/admin.json']) assert.equal((await request(url)).status,404);
    for (const driveUrl of ['https://evil.example/drive/folders/a','https://drive.google.com.evil.example/drive/folders/a','javascript:alert(1)','https://drive.google.com/file/d/a/view','https://user@drive.google.com/drive/folders/a']) assert.equal((await request('/api/albums','POST',{...album,driveUrl},cookie)).status,400);
    for (const change of [{ date:'2026-02-30' },{ category:'Invalid' },{ title:'' },{ thumbnail:'data:image/svg+xml;base64,PHN2Zz4=' },{ thumbnail:'data:image/png;base64,AAAA' }]) assert.equal((await request('/api/albums','POST',{...album,...change},cookie)).status,400);
    assert.equal((await request('/api/albums','POST',{ ...album, thumbnail:'data:image/png;base64,' + Buffer.alloc(3 * 1024 * 1024 + 1).toString('base64') },cookie)).status,413);
    const saved = await request('/api/albums','POST',album,cookie); assert.equal(saved.status,201); const id = (await saved.json()).album.id;
    assert.equal((await (await request('/api/albums')).json()).albums[0].title,album.title);
    await stop(); await start();
    assert.equal((await (await request('/api/albums')).json()).albums[0].id,id);
    assert.equal((await request('/api/albums/' + id,'DELETE',undefined,cookie)).status,401);
    const relogin = await request('/api/login','POST',credentials); const nextCookie = relogin.headers.get('set-cookie').split(';')[0];
    const persisted = (await (await request('/api/information')).json()).information;
    assert.equal(persisted.length,3); assert.equal(persisted.find(item => item.id === announcement.id).content,information.content);
    assert.equal(await (await request(announcement.attachment.url)).text(),'%PDF-1.4\n%%EOF');
    assert.equal((await request('/api/information/' + announcement.id,'DELETE',undefined,cookie)).status,401);
    for (const infoId of [announcement.id,textId,imageItem.id]) assert.equal((await request('/api/information/' + infoId,'DELETE',undefined,nextCookie)).status,200);
    assert.equal((await request(announcement.attachment.url)).status,404);
    assert.equal((await (await request('/api/information')).json()).information.length,0);
    assert.equal((await request('/data/information.json')).status,404);
    assert.equal((await request('/api/albums/' + id,'DELETE',undefined,nextCookie)).status,200);
    assert.equal((await (await request('/api/albums')).json()).albums.length,0);
    await request('/api/logout','POST',undefined,nextCookie);
    assert.equal((await request('/api/information','POST',information,nextCookie)).status,401);
    assert.equal((await request('/api/albums','POST',album,nextCookie)).status,401);
    for (let i = 0; i < 10; i++) await request('/api/login','POST',{ username:'admin',password:'wrong' });
    assert.equal((await request('/api/login','POST',credentials)).status,429);
  } finally {
    if (server?.listening) await stop();
    assert.ok(path.resolve(dataDir).startsWith(path.resolve(os.tmpdir()) + path.sep + 'ikm-test-'));
    fs.rmSync(dataDir,{ recursive:true,force:true });
  }
});
